# Generated by Django 3.2.4 on 2021-08-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('founded_date', models.DateField()),
                ('disbanded_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=40)),
                ('diesize', models.FloatField(blank=True, null=True)),
                ('transistors', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ALUs', models.SmallIntegerField()),
                ('max_memory_bus', models.SmallIntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lithography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('transistor_density', models.FloatField()),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lithography')),
                ('fab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fab')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsBoardSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('alus', models.SmallIntegerField()),
                ('max_memory_bus', models.SmallIntegerField()),
                ('gpu_clock', models.SmallIntegerField()),
                ('memory_clock', models.SmallIntegerField()),
                ('msrp', models.SmallIntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chipmaker')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gpu')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('gpu_clock', models.SmallIntegerField()),
                ('memory_clock', models.SmallIntegerField()),
                ('is_oc', models.BooleanField(default=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.graphicsboardsku')),
            ],
        ),
        migrations.CreateModel(
            name='GPUArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feature_support', models.CharField(max_length=40)),
                ('lithography', models.ManyToManyField(to='api.Lithography')),
            ],
        ),
        migrations.AddField(
            model_name='gpu',
            name='architecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gpuarchitecture'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chipmaker'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='lithography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lithography'),
        ),
    ]
